import type { Lang } from '@genoffice/i18n'
import type { CropEdge } from './image-dialogs'

// Shared accessible names for the crop edge handles, so every edge is reachable
// by keyboard and still announced in the editor's own language.
export const CROP_EDGE_LABELS: Record<Lang, Record<CropEdge, string>> = {
  zh: {
    nw: '左上边缘',
    n: '上边缘',
    ne: '右上边缘',
    e: '右边缘',
    se: '右下边缘',
    s: '下边缘',
    sw: '左下边缘',
    w: '左边缘',
  },
  en: {
    nw: 'Top left edge',
    n: 'Top edge',
    ne: 'Top right edge',
    e: 'Right edge',
    se: 'Bottom right edge',
    s: 'Bottom edge',
    sw: 'Bottom left edge',
    w: 'Left edge',
  },
  ja: {
    nw: '左上の辺',
    n: '上辺',
    ne: '右上の辺',
    e: '右辺',
    se: '右下の辺',
    s: '下辺',
    sw: '左下の辺',
    w: '左辺',
  },
  ko: {
    nw: '왼쪽 위 가장자리',
    n: '위쪽 가장자리',
    ne: '오른쪽 위 가장자리',
    e: '오른쪽 가장자리',
    se: '오른쪽 아래 가장자리',
    s: '아래쪽 가장자리',
    sw: '왼쪽 아래 가장자리',
    w: '왼쪽 가장자리',
  },
  fr: {
    nw: 'Bord supérieur gauche',
    n: 'Bord supérieur',
    ne: 'Bord supérieur droit',
    e: 'Bord droit',
    se: 'Bord inférieur droit',
    s: 'Bord inférieur',
    sw: 'Bord inférieur gauche',
    w: 'Bord gauche',
  },
  de: {
    nw: 'Oberer linker Rand',
    n: 'Oberer Rand',
    ne: 'Oberer rechter Rand',
    e: 'Rechter Rand',
    se: 'Unterer rechter Rand',
    s: 'Unterer Rand',
    sw: 'Unterer linker Rand',
    w: 'Linker Rand',
  },
  es: {
    nw: 'Borde superior izquierdo',
    n: 'Borde superior',
    ne: 'Borde superior derecho',
    e: 'Borde derecho',
    se: 'Borde inferior derecho',
    s: 'Borde inferior',
    sw: 'Borde inferior izquierdo',
    w: 'Borde izquierdo',
  },
  th: {
    nw: 'ขอบบนซ้าย',
    n: 'ขอบบน',
    ne: 'ขอบบนขวา',
    e: 'ขอบขวา',
    se: 'ขอบล่างขวา',
    s: 'ขอบล่าง',
    sw: 'ขอบล่างซ้าย',
    w: 'ขอบซ้าย',
  },
  id: {
    nw: 'Tepi kiri atas',
    n: 'Tepi atas',
    ne: 'Tepi kanan atas',
    e: 'Tepi kanan',
    se: 'Tepi kanan bawah',
    s: 'Tepi bawah',
    sw: 'Tepi kiri bawah',
    w: 'Tepi kiri',
  },
  ru: {
    nw: 'Верхний левый край',
    n: 'Верхний край',
    ne: 'Верхний правый край',
    e: 'Правый край',
    se: 'Нижний правый край',
    s: 'Нижний край',
    sw: 'Нижний левый край',
    w: 'Левый край',
  },
  ar: {
    nw: 'الحافة العلوية اليسرى',
    n: 'الحافة العلوية',
    ne: 'الحافة العلوية اليمنى',
    e: 'الحافة اليمنى',
    se: 'الحافة السفلية اليمنى',
    s: 'الحافة السفلية',
    sw: 'الحافة السفلية اليسرى',
    w: 'الحافة اليسرى',
  },
  pt: {
    nw: 'Borda superior esquerda',
    n: 'Borda superior',
    ne: 'Borda superior direita',
    e: 'Borda direita',
    se: 'Borda inferior direita',
    s: 'Borda inferior',
    sw: 'Borda inferior esquerda',
    w: 'Borda esquerda',
  },
  it: {
    nw: 'Bordo superiore sinistro',
    n: 'Bordo superiore',
    ne: 'Bordo superiore destro',
    e: 'Bordo destro',
    se: 'Bordo inferiore destro',
    s: 'Bordo inferiore',
    sw: 'Bordo inferiore sinistro',
    w: 'Bordo sinistro',
  },
  pl: {
    nw: 'Górna lewa krawędź',
    n: 'Górna krawędź',
    ne: 'Górna prawa krawędź',
    e: 'Prawa krawędź',
    se: 'Dolna prawa krawędź',
    s: 'Dolna krawędź',
    sw: 'Dolna lewa krawędź',
    w: 'Lewa krawędź',
  },
  cs: {
    nw: 'Horní levý okraj',
    n: 'Horní okraj',
    ne: 'Horní pravý okraj',
    e: 'Pravý okraj',
    se: 'Dolní pravý okraj',
    s: 'Dolní okraj',
    sw: 'Dolní levý okraj',
    w: 'Levý okraj',
  },
  nl: {
    nw: 'Linkerbovenrand',
    n: 'Bovenrand',
    ne: 'Rechterbovenrand',
    e: 'Rechterrand',
    se: 'Rechteronderrand',
    s: 'Onderrand',
    sw: 'Linkeronderrand',
    w: 'Linkerrand',
  },
  ms: {
    nw: 'Tepi kiri atas',
    n: 'Tepi atas',
    ne: 'Tepi kanan atas',
    e: 'Tepi kanan',
    se: 'Tepi kanan bawah',
    s: 'Tepi bawah',
    sw: 'Tepi kiri bawah',
    w: 'Tepi kiri',
  },
  he: {
    nw: 'הקצה העליון השמאלי',
    n: 'הקצה העליון',
    ne: 'הקצה העליון הימני',
    e: 'הקצה הימני',
    se: 'הקצה התחתון הימני',
    s: 'הקצה התחתון',
    sw: 'הקצה התחתון השמאלי',
    w: 'הקצה השמאלי',
  },
  hi: {
    nw: 'ऊपरी बायाँ किनारा',
    n: 'ऊपरी किनारा',
    ne: 'ऊपरी दायाँ किनारा',
    e: 'दायाँ किनारा',
    se: 'निचला दायाँ किनारा',
    s: 'निचला किनारा',
    sw: 'निचला बायाँ किनारा',
    w: 'बायाँ किनारा',
  },
  'zh-TW': {
    nw: '左上邊緣',
    n: '上邊緣',
    ne: '右上邊緣',
    e: '右邊緣',
    se: '右下邊緣',
    s: '下邊緣',
    sw: '左下邊緣',
    w: '左邊緣',
  },
  vi: {
    nw: '左上邊緣',
    n: '上邊緣',
    ne: '右上邊緣',
    e: '右邊緣',
    se: '右下邊緣',
    s: '下邊緣',
    sw: '左下邊緣',
    w: '左邊緣',
  },
}
